//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfabetForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controls
    {
        public int ID { get; set; }
        public string FormID { get; set; }
        public string ControlID { get; set; }
        public Nullable<int> PosX { get; set; }
        public Nullable<int> PosY { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Controls1 { get; set; }
        public Nullable<bool> BeingModified { get; set; }
    }
}
